### ISSUE TITLE
Hover not working on dirty files

### ISSUE THREAD

**Issue by ch0mler** [infosec-intern/vscode-yara-abandoned#1]
Looks like the hover provider isn't properly searching un-saved documents. Might be a more common problem

```
Could not offer definition hover: Could not offer definition for symbol '$a': Start position cannot be <class 'NoneType'>. Must be Position
```

![image](https://user-images.githubusercontent.com/56052936/70560588-1f005e80-1b46-11ea-853d-24f819212f4c.png)

**Comment by infosec-intern** [comment]
Fixed in 248c602cdd4367d9695391a356334dbd747f2440
