### ISSUE TITLE
New operator keywords

### ISSUE THREAD

**Issue by tlansec** [infosec-intern/vscode-yara-abandoned#10]
In the next release of YARA there will be a number of new keywords supported which should be added under "keyword.other.misc.yara":

endswith
iendswith
icontains
startswith
istartswith 

See:

https://github.com/VirusTotal/yara/pull/1357/commits/6c7aa9c5e23c69a8519b1f6938f5000d9396c38c

**Comment by infosec-intern** [comment]
Thanks for the heads up on this! I'll push an update out when these are added to the next release

**Comment by infosec-intern** [comment]
Just added in [v1.4.0](https://github.com/infosec-intern/textmate-yara/releases/tag/v1.4.0). Thanks for the heads up!
