### ISSUE TITLE
Possible to publish this extension on Open VSX?

### ISSUE THREAD

**Issue by 3c7** [infosec-intern/vscode-yara-abandoned#8]
Hey @infosec-intern, thanks for your work, this is a great extension. 
Would it be possible to publish this VS Code extension to https://open-vsx.org/? This way people using [VS Codium](https://github.com/VSCodium/vscodium) (and similar) would also be able to use it.

**Comment by infosec-intern** [comment]
Whoa, very interesting. I didn't know this was even a thing; thanks for pointing this out! I'll need to dig into this more, but I don't have any issues publishing there as well. I'll update this when I have something up

**Comment by 3c7** [comment]
Great! Yeah, I also didn't know about open vsx before and discovered it because I missed the yara extension in VS Codium. :)

**Comment by 3c7** [comment]
Maybe this is helpful: https://github.com/HaaLeo/publish-vscode-extension

**Comment by infosec-intern** [comment]
https://open-vsx.org/extension/infosec-intern/yara

The extension is live on the OpenVSX marketplace :partying_face:! I just noticed the the images in the README aren't rendering, and I'll fix that for the next update. Gonna close this issue, but if you notice anything missing, please don't hesitate to reach back out.

**Comment by 3c7** [comment]
Great, thank you!
